Repository FromDoppler/doppler-account-plans, pull requests merged in 2024-04, with the labels that each got.

#389 DAT-1930 - Calculate landing plan fee
  Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs
  Doppler.AccountPlans.Test/GetCalculateUpgradeLandingPlanCostTest.cs
  Doppler.AccountPlans/Controllers/AccountPlansController.cs
  Doppler.AccountPlans/Model/LandingPlanSummary.cs
  Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Labels: size/L

#390 [DAT-1981] Calculation of the total monthly landing plan
  Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs
  Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Labels: size/S

#391 [DAT-1952] Discount already paid landing plans
  Doppler.AccountPlans.Test/CalculateUpgradeCostTest.cs
  Doppler.AccountPlans/Controllers/AccountPlansController.cs
  Doppler.AccountPlans/Enums/BillingCreditTypeEnum.cs
  Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
  Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs
  Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Labels: size/M

#392 [DAT-1983] - Update logic to calculate the positive balance
  Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
  Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Labels: size/M

#394 fix issue to calculate the discount of the payment already paid
  Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Labels: size/XS
