Repository FromDoppler/doppler-account-plans, pull requests merged in 2024-09, with the labels that each got.

#430 Fix issue with promocode
  Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromChatPlanHelper.cs
Labels: size/XS

#434 Filter non-active conversation plans
  Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
Labels: size/XS

#437 [No-Task] - Fix issue calculate landing amount
  Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Labels: size/S

#438 [no-task] fix issue for calculate landing amount
  Doppler.AccountPlans/Controllers/AccountPlansController.cs
Labels: size/XS

#439 [no-task] fix issue when calculate next invoice date
  Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromChatPlanHelper.cs
  Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromMarketingPlanHelper.cs
  Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Labels: size/XS

#440 [no-task] Add endpoint to get custom conversations plans
  Doppler.AccountPlans/Controllers/AccountPlansController.cs
  Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
  Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs
Labels: size/M
