Repository FromDoppler/doppler-account-plans, pull requests merged in 2025-04, with the labels that each got.

#485 Create endpoint to get addon plan details
  Doppler.AccountPlans/Controllers/AccountPlansController.cs
  Doppler.AccountPlans/Enums/AddOnType.cs
  Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
  Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs
  Doppler.AccountPlans/Mappers/IAddOnMapper.cs
  Doppler.AccountPlans/Mappers/OnSiteMapper.cs
  Doppler.AccountPlans/Mappers/PushNotificationMapper.cs
  Doppler.AccountPlans/Model/AddOnPlan.cs
Labels: size/L

#486 [DAT-2427] - Calculate amount for the push notification plan
  Doppler.AccountPlans/Controllers/AccountPlansController.cs
  Doppler.AccountPlans/Enums/PlanTypeEnum.cs
  Doppler.AccountPlans/Helpers/CalculateAmountDetailsFromPushNotificationPlanHelper.cs
  Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
  Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs
  Doppler.AccountPlans/Utils/CalculateUpgradeCostHelper.cs
Labels: size/L

#488 Dat 2428
  Doppler.AccountPlans/Controllers/AccountPlansController.cs
  Doppler.AccountPlans/Infrastructure/AccountPlansRepository.cs
  Doppler.AccountPlans/Infrastructure/IAccountPlansRepository.cs
  Doppler.AccountPlans/Mappers/IAddOnMapper.cs
  Doppler.AccountPlans/Mappers/OnSiteMapper.cs
  Doppler.AccountPlans/Mappers/PushNotificationMapper.cs
  Doppler.AccountPlans/Model/BasePlanInformation.cs
  Doppler.AccountPlans/Model/ConversationPlanInformation.cs
  Doppler.AccountPlans/Model/LandingPlanInformation.cs
  Doppler.AccountPlans/Model/OnSitePlanInformation.cs
  Doppler.AccountPlans/Model/PushNotificationPlanInformation.cs
Labels: size/M

#491 feat: update to use netcore 9.0
  Dockerfile
  Doppler.AccountPlans.Test/AuthorizationTest.cs
  Doppler.AccountPlans.Test/Doppler.AccountPlans.Test.csproj
  Doppler.AccountPlans/Doppler.AccountPlans.csproj
Labels: size/S
